# Generated by Django 5.0 on 2024-02-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_carpenter',
            field=models.BooleanField(default=False, verbose_name='Is carpenter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_electrician',
            field=models.BooleanField(default=False, verbose_name='Is electrician'),
        ),
    ]
