# Generated by Django 5.0 on 2024-02-05 14:13

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_is_carpenter_alter_user_is_electrician'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.user_profile_picture_path),
        ),
    ]
