# Generated by Django 5.0 on 2024-03-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_servicerequest_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.servicerequest')),
            ],
            options={
                'ordering': ['-update_time'],
            },
        ),
    ]
