# Generated by Django 5.0 on 2024-03-04 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
