# Generated by Django 5.0 on 2024-03-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_review_provider_alter_review_reviewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
