# Generated by Django 5.0 on 2024-03-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='customer',
        ),
    ]
